import json
import os
import re
import sys
from typing import Any, Dict, Optional, Tuple

import requests

from langchain_agent import process_with_ai
from github_api import (
    get_issue,
    post_pr_comment,
    receipt_already_posted,
)
from pr_parser import parse_pr_body, parse_bounty_from_issue_title


DEFAULT_BOUNTY = os.getenv("GITPAY_DEFAULT_BOUNTY", "1.0 USDC")
X402_TIMEOUT = int(os.getenv("X402_TIMEOUT", "20"))


def load_event() -> Dict[str, Any]:
    path = os.getenv("GITHUB_EVENT_PATH")
    if not path:
        raise RuntimeError("Missing GITHUB_EVENT_PATH")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def extract_repo(event: Dict[str, Any]) -> Tuple[str, str]:
    repo = event.get("repository") or {}
    owner = (repo.get("owner") or {}).get("login")
    name = repo.get("name")
    if not owner or not name:
        raise RuntimeError("Cannot read owner/repo from event")
    return owner, name


def extract_pr(event: Dict[str, Any]) -> Tuple[int, str, bool]:
    pr = event.get("pull_request") or {}
    pr_number = pr.get("number")
    pr_body = pr.get("body") or ""
    merged = bool(pr.get("merged"))
    if not pr_number:
        raise RuntimeError("Cannot read pull_request.number from event")
    return int(pr_number), str(pr_body), merged


def find_tx_hash(text: str) -> Optional[str]:
    m = re.search(r"\b0x[a-fA-F0-9]{64}\b", text or "")
    return m.group(0) if m else None


def build_receipt(
    *,
    status: str,
    owner: str,
    repo: str,
    pr_number: int,
    issue_number: Optional[int],
    amount: str,
    wallet: Optional[str],
    payout_tx: Optional[str],
    funded_tx: Optional[str],
) -> str:
    lines = []
    lines.append("✅ **GitPay Receipt**")
    lines.append("")
    lines.append(f"**Repo:** {owner}/{repo}")
    lines.append(f"**PR:** #{pr_number}")
    if issue_number:
        lines.append(f"**Issue:** #{issue_number}")
    lines.append(f"**Status:** {status}")
    lines.append(f"**Amount:** {amount}")
    if wallet:
        lines.append(f"**Wallet:** `{wallet}`")

    if funded_tx:
        lines.append(f"**Funding Proof (x402):** `{funded_tx}`")

    if payout_tx:
        lines.append(f"**Tx:** `{payout_tx}`")
        lines.append(f"**Explorer:** https://explorer.cronos.org/testnet/tx/{payout_tx}")

    lines.append("")
    lines.append("_Auto-generated by GitPay (prototype)._")
    return "\n".join(lines)


def x402_status(owner: str, repo: str, issue_number: int) -> Tuple[bool, Optional[dict]]:
    base = (os.getenv("X402_SERVICE_URL") or "").strip().rstrip("/")
    if not base:
        raise RuntimeError("Missing X402_SERVICE_URL (set in GitHub Secrets)")

    url = f"{base}/bounties/status"
    r = requests.get(
        url,
        params={"owner": owner, "repo": repo, "issueNumber": issue_number},
        timeout=X402_TIMEOUT,
    )

    if r.status_code == 404:
        return False, None

    r.raise_for_status()
    data = r.json()
    funded = bool(data.get("funded"))
    record = data.get("record")
    return funded, record


def main() -> int:
    event = load_event()
    owner, repo = extract_repo(event)
    pr_number, pr_body, merged = extract_pr(event)

    if not merged:
        print("PR not merged. Exiting.")
        return 0

    # Idempotency: do not pay twice
    if receipt_already_posted(owner, repo, pr_number):
        print("Receipt already posted. Exiting.")
        return 0

    parsed = parse_pr_body(pr_body)
    issue_number = parsed.issue_number
    wallet = parsed.wallet

    if not issue_number:
        post_pr_comment(
            owner,
            repo,
            pr_number,
            build_receipt(
                status="Skipped (missing `Closes #<issue>` in PR body)",
                owner=owner,
                repo=repo,
                pr_number=pr_number,
                issue_number=None,
                amount=DEFAULT_BOUNTY,
                wallet=wallet,
                payout_tx=None,
                funded_tx=None,
            ),
        )
        return 0

    # Verify escrow/funding via x402 (tunnel)
    funded, record = x402_status(owner, repo, issue_number)
    funded_tx = None
    if record:
        funded_tx = record.get("fundedTxHash") or record.get("funded_tx_hash")

    if not funded:
        post_pr_comment(
            owner,
            repo,
            pr_number,
            build_receipt(
                status=f"Skipped (Issue #{issue_number} is NOT funded in x402)",
                owner=owner,
                repo=repo,
                pr_number=pr_number,
                issue_number=issue_number,
                amount=DEFAULT_BOUNTY,
                wallet=wallet,
                payout_tx=None,
                funded_tx=funded_tx,
            ),
        )
        return 0

    # Determine bounty amount (from GitHub issue title like: [50 USDC] Fix bug)
    issue = get_issue(owner, repo, issue_number)
    issue_title = issue.get("title") or ""
    bounty = parse_bounty_from_issue_title(issue_title) or DEFAULT_BOUNTY

    # Trigger AI payout
    result_text = process_with_ai(pr_body, issue_number=issue_number, default_amount=bounty)
    payout_tx = find_tx_hash(result_text)

    status = "Paid ✅" if payout_tx else ("No wallet found" if "No wallet found" in result_text else "Processed")

    post_pr_comment(
        owner,
        repo,
        pr_number,
        build_receipt(
            status=status,
            owner=owner,
            repo=repo,
            pr_number=pr_number,
            issue_number=issue_number,
            amount=bounty,
            wallet=wallet,
            payout_tx=payout_tx,
            funded_tx=funded_tx,
        ),
    )

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"Action runner failed: {e}", file=sys.stderr)
        raise
